### ISSUE TITLE
 Expected n_neighbors <= n_samples,  but n_samples = 1, n_neighbors = 2

### ISSUE THREAD

**Issue by peerawit503** [beesightsoft/bss-rd-student#3]
Hi Guy
I try to run your code and I got an error

Traceback (most recent call last):
  File "face_recognition_knn.py", line 223, in <module>
    predictions = predict(full_file_path, model_path="trained_knn_model.clf")
  File "face_recognition_knn.py", line 153, in predict
    closest_distances = knn_clf.kneighbors(faces_encodings, n_neighbors=2) # return the closest distances of a current point to other neighbors
  File "/usr/local/lib/python3.7/site-packages/sklearn/neighbors/base.py", line 416, in kneighbors
    (train_size, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 1, n_neighbors = 2

what should I do

**Comment by ltphy** [comment]
As stated by the error, the number of samples is only 1, but the number of neighbors is 2. Your model only have 1 class trained by KNN. You better check your dataset.
My suggestions: Do some preprocessing with the data. For example, grayscale.
